version: '3'

services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    command: >
      sh -c "apt-get update --yes --quiet > /dev/null &&
             apt-get upgrade --yes --quiet > /dev/null &&
             apt-get install chromium --quiet --yes > /dev/null &&
             cd /app/screenshot-api && 
             dotnet dev-certs https --trust && 
             dotnet restore &&
             dotnet watch run"
    volumes:
      - './:/app'
    ports:
      - 4000:4000
      - 4001:4001
    environment:
      'ASPNETCORE_HTTPS_PORT': '4001'
      'ASPNETCORE_URLS': 'http://+:4000;https://+:4001'
      'ASPNETCORE_ENVIRONMENT': 'Development'
      'TOKEN': ${TOKEN}
      'PUPPETEER_SKIP_CHROMIUM_DOWNLOAD': 'true'
      'WARMINUP_URL': ${WARMINUP_URL}
      'USER_AGENT': ${USER_AGENT}
      'CHROMIUM_EXECUTABLEPATH': ${CHROMIUM_EXECUTABLEPATH}
